/**
 * VideoProps — single typed contract for the YouTube market report pipeline.
 *
 * Carries every figure, asset path, citation, and timing value needed to render
 * any composition (landscape YouTube long-form 1920x1080, portrait Reels/Shorts
 * 1080x1920, or any subset cut). Generated by `generate-props.ts` from Supabase
 * + Spark cross-checks. Consumed by `generate-script.ts`, every scene
 * component, and the YouTube upload function.
 *
 * Hard rules (see skills/youtube-market-reports/query-rules.md):
 *   - Every numeric figure traces to a Citation in `citations`.
 *   - `monthsOfSupply` is the SFR-only manual computation per Template 11.
 *     Never the value from `market_pulse_live.months_of_supply`.
 *   - DOM metrics use the `days_to_pending` column. Never DaysOnMarket or
 *     CloseDate - OnMarketDate.
 *   - All closed-sales aggregations applied UF1 (ClosePrice >= 10000).
 *   - All ratio aggregations applied UF2 (sale_to_final_list_ratio in
 *     [0.5, 1.5]).
 *   - All MoS computations applied UF3 (SFR filter on both CTEs).
 */

// ---------------------------------------------------------------------------
// Markets (Central Oregon service area covered by the channel)
// ---------------------------------------------------------------------------

export type Market =
  | 'Bend'
  | 'Redmond'
  | 'Sisters'
  | 'Sunriver'
  | 'La Pine'
  | 'Jefferson County'
  | 'Crook County';

export const MARKETS: readonly Market[] = [
  'Bend',
  'Redmond',
  'Sisters',
  'Sunriver',
  'La Pine',
  'Jefferson County',
  'Crook County',
] as const;

// ---------------------------------------------------------------------------
// Orientation + composition geometry
// ---------------------------------------------------------------------------

export type Orientation = 'landscape' | 'portrait';

/** Composition sizes per orientation. Landscape = YouTube long-form. Portrait = Reels/Shorts. */
export const COMPOSITION_SIZE = {
  landscape: { width: 1920, height: 1080 },
  portrait: { width: 1080, height: 1920 },
} as const satisfies Record<Orientation, { width: number; height: number }>;

export const FPS = 30 as const;

// ---------------------------------------------------------------------------
// Time periods
// ---------------------------------------------------------------------------

/** Inclusive ISO-date window. Always interpreted in America/Los_Angeles. */
export interface DateWindow {
  start: string; // 'YYYY-MM-DD'
  end: string;   // 'YYYY-MM-DD'
}

export interface VideoPeriod {
  /** Human label, e.g. "April 2026". Used in titles and VO. */
  label: string;
  /** Machine-readable month identifier, e.g. "2026-04". */
  monthId: string;
  /** Calendar month name, e.g. "April". */
  monthName: string;
  /** Calendar year, e.g. 2026. */
  year: number;
  /** Current period close-date window. */
  current: DateWindow;
  /** Year-prior comparison window for YoY math. */
  priorYear: DateWindow;
  /** 24-month trailing window for time-series charts. */
  trailing24mo: DateWindow;
}

// ---------------------------------------------------------------------------
// Direction + verdict tokens
// ---------------------------------------------------------------------------

export type Direction = 'up' | 'down' | 'flat';

export type MarketCondition =
  | "Seller's Market"
  | 'Balanced Market'
  | "Buyer's Market";

// ---------------------------------------------------------------------------
// Citations — every figure must trace to one of these
// ---------------------------------------------------------------------------

/** Standard citation for a single Supabase-derived figure. */
export interface SupabaseCitation {
  kind: 'supabase';
  metric: string;
  value: number;
  display: string;
  source: 'Supabase listings' | 'Supabase listing_history' | 'Supabase price_history';
  table: string;
  filters: string;
  rowCount: number;
  query: string;
  /** Spark API cross-check value. Required for any figure also available in Spark. */
  sparkValue?: number;
  /** Absolute |delta| as a percentage. Must be < 1.0 to ship. */
  sparkDeltaPct?: number;
  fetchedAtIso: string;
}

/**
 * Special-case citation for Months of Supply per query-rules.md Template 11.
 * Required fields make the manual SFR-only computation auditable.
 */
export interface MonthsOfSupplyCitation {
  kind: 'months_of_supply';
  metric: 'Months of Supply';
  value: number;
  display: string;
  active: number;
  closedLookback: number;
  lookbackDays: number;
  formula: string; // e.g. "active / (closed_180d / 180 * 30)"
  source: 'Supabase listings (SFR-only manual)';
  sparkActive?: number;
  sparkDeltaPct?: number;
  fetchedAtIso: string;
}

/** Citation for a third-party reference figure (NAR, Census, BLS, etc.). */
export interface ExternalCitation {
  kind: 'external';
  metric: string;
  value: number;
  display: string;
  source: string;
  url: string;
  fetchedAtIso: string;
}

export type Citation = SupabaseCitation | MonthsOfSupplyCitation | ExternalCitation;

// ---------------------------------------------------------------------------
// Voice + alignment
// ---------------------------------------------------------------------------

/** One word from ElevenLabs forced-alignment, indexed in seconds and frames. */
export interface AlignmentWord {
  word: string;
  /** Seconds from segment start. */
  startSeconds: number;
  endSeconds: number;
  /** Math.round(startSeconds * 30) — pre-computed for Remotion convenience. */
  startFrame: number;
  endFrame: number;
  /** Index into `Voice.segments` so captions know which scene they belong to. */
  segmentIndex: number;
}

export interface VoiceSegment {
  /** Scene this VO segment belongs to. 0-8 maps to Scene 0–8. */
  sceneIndex: number;
  /** Path to the rendered MP3, relative to the Remotion `public/` root. */
  audioPath: string;
  /** Length of this segment's audio in seconds. */
  durationSeconds: number;
  /** ElevenLabs request text, post-IPA-tagging, post-numbers-spelled-out. */
  text: string;
  /** Word-level alignment for this segment. */
  words: AlignmentWord[];
}

export interface Voice {
  voiceId: string; // Always Victoria 'qSeXEcewz7tA0Q0qk9fH'
  modelId: string; // Always 'eleven_turbo_v2_5'
  /** Path to the alignment JSON output by ElevenLabs forced-alignment. */
  alignmentPath: string;
  /** Per-scene VO segments in narration order. */
  segments: VoiceSegment[];
  /** Sum of all segment durations. */
  totalDurationSeconds: number;
}

// ---------------------------------------------------------------------------
// Per-scene data types
// ---------------------------------------------------------------------------

/** Hook anchor stat — picked from the most dramatic figure for this period. */
export type AnchorStatName =
  | 'median_price'
  | 'median_days_to_pending'
  | 'months_of_supply'
  | 'sale_to_list'
  | 'absorption_rate'
  | 'inventory_yoy';

export interface Scene0Hook {
  medianPrice: number;
  closedCount: number;
  medianDaysToPending: number;
  /** Direction of the headline metric vs. prior comparable period. */
  direction: Direction;
  /** Word for VO, e.g. "strong", "soft", "shifting". Must be data-derived. */
  characterization: string;
  /** Which metric carries the hook this episode. */
  anchorStatName: AnchorStatName;
  /** Display string for the anchor stat, e.g. "$725K" or "12 days". */
  anchorStatDisplay: string;
  /** Raw numeric value behind anchorStatDisplay. */
  anchorStatValue: number;
}

export interface Scene1Title {
  monthYear: string; // "April 2026"
  miniAgenda: readonly string[]; // ["Prices", "Inventory", "Days to Pending", "Neighborhood Breakdown"]
}

export interface MonthlyMedianPoint {
  /** First-of-month date as 'YYYY-MM-DD'. */
  month: string;
  medianPrice: number;
  salesCount: number;
}

export interface Scene2MedianPrice {
  /** 24 monthly points, oldest first. */
  monthlySeries: MonthlyMedianPoint[];
  /** Current period median sale price. */
  currentMedian: number;
  /** Same period last year median sale price. */
  priorYearMedian: number;
  yoyPct: number;
  yoyDirection: Direction;
  /** Human label of the current period for VO, e.g. "April". */
  currentMonthLabel: string;
  /** One-sentence trend interpretation derived from the data. */
  trendDescription: string;
  /** One-sentence "what this means" follow-up. */
  interpretation: string;
}

export type PropertySubType =
  | 'Single Family Residence'
  | 'Condominium'
  | 'Townhouse'
  | 'Manufactured On Land'
  | 'Manufactured Home';

export interface PricePerSqFtRow {
  propertySubType: PropertySubType;
  /** Median $/sqft this period. */
  medianPpsf: number;
  /** Sales count this period. */
  sales: number;
  /** Median $/sqft same period prior year (for YoY bars). */
  priorYearMedianPpsf: number;
  /** YoY % change as a signed number, e.g. -2.5. */
  yoyPct: number;
}

export interface Scene3PricePerSqFt {
  byPropertyType: PricePerSqFtRow[];
  /** Convenience: SFR row teased out for the VO template. */
  sfrPpsf: number;
  sfrPct: number;
  sfrDirection: Direction;
  /** Pre-formatted comparison clauses derived from byPropertyType. */
  condoComparison: string;
  manufacturedComparison: string;
}

export interface MonthlyInventoryPoint {
  month: string; // 'YYYY-MM-DD'
  sfrActive: number;
  condoActive: number;
  landActive: number;
}

export interface Scene4Inventory {
  /** 24-month stacked area data. */
  monthlySeries: MonthlyInventoryPoint[];
  /** SFR active inventory now (for the gauge + VO). */
  activeCount: number;
  /** Active inventory same period prior year. */
  activeCountPriorYear: number;
  inventoryPct: number;
  inventoryDirection: Direction;
  /** Closed sales in the lookback window (default 180d). */
  closedLookback: number;
  lookbackDays: number;
  /** Closed sales per month over the lookback window. */
  monthlyCloseRate: number;
  /** SFR-only manual months of supply (Template 11). */
  monthsOfSupply: number;
  marketCondition: MarketCondition;
  /** One-sentence VO line tying MoS to the market verdict. */
  marketConditionExplanation: string;
}

export interface DomByPriceBandRow {
  /** Price band label, e.g. "Under $500K". */
  priceBand: string;
  sales: number;
  medianDaysToPending: number;
  dtpP25: number;
  dtpP75: number;
}

export interface Scene5DaysToPending {
  byPriceBand: DomByPriceBandRow[];
  /** SFR-only manual absorption rate as a percentage. */
  absorptionRatePct: number;
  /** SFR-only sell-through rate over the trailing 90 days. */
  sellThroughRate90d: number;
  /** Median days_to_pending across all bands. */
  medianDaysToPending: number;
  /** Convenience accessors per VO template (median DOM per band). */
  domUnder500k: number;
  dom500to700k: number;
  dom700kTo1m: number;
  dom1mPlus: number;
  /** One-sentence VO interpretation of the absorption rate. */
  absorptionInterpretation: string;
}

export interface ZipMetricsRow {
  postalCode: string;
  /** Friendly area name, e.g. "West Side", "NW Crossing". */
  areaName: string;
  /** Latitude/longitude of the ZIP centroid for camera flythrough. */
  centroid: { lat: number; lng: number };
  sales: number;
  medianPrice: number;
  medianPpsf: number;
  medianDaysToPending: number;
  /** YoY % change in median price. */
  yoyPct: number;
}

export interface Scene6Neighborhoods {
  byZip: ZipMetricsRow[];
  /** ZIP code with the largest YoY appreciation this period. */
  hottestZip: string;
  hottestYoyPct: number;
  /** Most expensive ZIP this period (for VO line). */
  highestPriceZip: string;
  highestPriceMedian: number;
  /** Lowest median price ZIP this period (for VO line). */
  bestValueZip: string;
  bestValueMedian: number;
}

export interface Scene7Takeaways {
  /** Median sale-to-final-list ratio, in percentage form (e.g. 97.1). */
  medianSaleToListPct: number;
  /** 2–3 buyer-side takeaways, each one short sentence. */
  buyerTakeaways: readonly string[];
  /** 2–3 seller-side takeaways, each one short sentence. */
  sellerTakeaways: readonly string[];
  /** Best-value ZIP (lowest median $/sqft) for the buyer panel. */
  bestValueZip: string;
  bestValueZipPpsf: number;
}

export interface Scene8Cta {
  /** Date when the next report drops, e.g. "May 24, 2026". */
  nextReportDate: string;
  url: string;   // 'ryan-realty.com'
  phone: string; // '541.213.6706'
}

// ---------------------------------------------------------------------------
// Asset paths
// ---------------------------------------------------------------------------

/**
 * Paths to all rendered/fetched assets, relative to the Remotion `public/`
 * root. Keys map to scenes; optional fields fall back to lower-cost sources.
 */
export interface VideoAssets {
  /** Earth zoom or 3D Tiles JPEG sequence/MP4 for Scene 0. */
  hookBackground: string;
  /** Optional B-roll loop underlayer for Scene 2 (15% opacity). */
  scene2Broll?: string;
  /** Optional B-roll intercut for Scene 4 Part B (full opacity). */
  scene4Broll?: string;
  /** Google 3D Tiles flyover MP4 for Scene 6 Part A. */
  scene6Aerial: string;
  /** ZIP boundary GeoJSON for Scene 6 SVG overlay. */
  scene6ZipGeoJson: string;
  /** Depth-parallax photo + depth map pair for Scene 7. */
  scene7Photo: string;
  scene7DepthMap: string;
  /** Brand assets — paths to logo and audio stings. */
  endCardLogo: string;     // listing_video_v4/public/brand/stacked_logo_white.png
  brandSting: string;      // path under video/brand-outro/
  /** Background music bed, looped at -18 to -22 dB. */
  musicBed: string;
  /** YouTube thumbnail variants for A/B testing. */
  thumbnailVariants: string[];
}

// ---------------------------------------------------------------------------
// Scene timing — durations in frames at FPS = 30
// ---------------------------------------------------------------------------

export interface SceneDurations {
  scene0Hook: number;
  scene1Title: number;
  scene2MedianPrice: number;
  scene3PricePerSqFt: number;
  scene4Inventory: number;
  scene5DaysToPending: number;
  scene6Neighborhoods: number;
  scene7Takeaways: number;
  scene8Cta: number;
}

// ---------------------------------------------------------------------------
// YouTube publish metadata (computed by generate-script, consumed by upload)
// ---------------------------------------------------------------------------

export interface YouTubeMetadata {
  /** Under 60 chars. Geographic + topical + data hook. */
  title: string;
  /** A/B test alternates. */
  titleVariants: readonly string[];
  /** First 200 chars contain the primary keyword. Includes timestamps. */
  description: string;
  tags: readonly string[];
  /** YouTube category ID (22 = People & Blogs, 25 = News & Politics). */
  categoryId: 22 | 25;
  /** Hashtags for the description footer. */
  hashtags: readonly string[];
  /** Publish-time hint. ISO 8601 in America/Los_Angeles. */
  publishAtIso: string;
}

// ---------------------------------------------------------------------------
// Top-level VideoProps — the contract every component reads
// ---------------------------------------------------------------------------

/** Schema version. Bump on any breaking change to the interface. */
export const VIDEO_PROPS_SCHEMA_VERSION = '1.0.0' as const;

export interface VideoProps {
  /** Schema version of this props object. Validated at render time. */
  schemaVersion: typeof VIDEO_PROPS_SCHEMA_VERSION;
  /** Which Central Oregon market this video covers. */
  market: Market;
  /** Time window covered. */
  period: VideoPeriod;
  /** Composition orientation. Landscape = YouTube long-form. Portrait = Reels/Shorts. */
  orientation: Orientation;
  /** Episode identifier, e.g. "2026-04-bend-monthly". */
  episodeId: string;
  /** ISO 8601 timestamp when this props object was generated. */
  generatedAtIso: string;

  /** Per-scene data. */
  scene0: Scene0Hook;
  scene1: Scene1Title;
  scene2: Scene2MedianPrice;
  scene3: Scene3PricePerSqFt;
  scene4: Scene4Inventory;
  scene5: Scene5DaysToPending;
  scene6: Scene6Neighborhoods;
  scene7: Scene7Takeaways;
  scene8: Scene8Cta;

  /** Frame durations per scene at FPS=30. */
  sceneDurations: SceneDurations;

  /** Voice + alignment. */
  voice: Voice;

  /** Asset file paths. */
  assets: VideoAssets;

  /** Citation per figure. Empty array = non-ship. */
  citations: readonly Citation[];

  /** YouTube publish metadata. Optional on portrait/Shorts compositions. */
  youtube?: YouTubeMetadata;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Total composition duration in frames at FPS=30. */
export function computeTotalDurationFrames(durations: SceneDurations): number {
  return (
    durations.scene0Hook +
    durations.scene1Title +
    durations.scene2MedianPrice +
    durations.scene3PricePerSqFt +
    durations.scene4Inventory +
    durations.scene5DaysToPending +
    durations.scene6Neighborhoods +
    durations.scene7Takeaways +
    durations.scene8Cta
  );
}

/** Convert seconds to frames at FPS=30, with a 1-frame floor. */
export function secondsToFrames(seconds: number): number {
  return Math.max(1, Math.round(seconds * FPS));
}

/** Resolve composition pixel dimensions for a given orientation. */
export function dimensionsFor(orientation: Orientation): { width: number; height: number } {
  return COMPOSITION_SIZE[orientation];
}
