// Tumalo.tsx — 19496 Tumalo Reservoir Rd VIRAL CUT v3 ("Blonde Waterfall" build)
// 1080x1920 portrait, 30fps, 42.6s. List price $1,350,000, Active.
// (Was 45.0s — eagle beat removed per Matt 2026-04-26, closing aerials
// shifted left by 2.4s, reveal moved 40.0s → 37.6s, total trimmed by 2.4s.)
//
// v3 changes vs v2:
//   - DepthParallaxBeat on every photo beat using REAL MiDaS depth maps
//     (small model, MPS-accelerated). Layer PNGs live in
//     public/v5_library/depth/tumalo/<slug>/ and were generated by
//     /tmp/run_midas_tumalo.py (one-shot wrapper around
//     video_production_skills/depth_parallax/{generate_depth_map,layer_separator}.py).
//     Earlier v3 cut used synthetic vertical-band masks because MiDaS install
//     hit a disk-space wall — 14 stale worktrees were pruned to free 14 GB
//     and torch+timm+opencv installed cleanly thereafter.
//   - LightLeakTransition at 25% mark (beat 4→5 boundary, ~10.8s).
//   - WhipPanTransition at 50% mark (beat 8→9 boundary, ~20.4s).
//   - Beat-sync grid at 100 BPM (0.6s sub-beat). Cuts land on multiples of
//     0.6s. Photo beats run 4–5 sub-beats (2.4–3.0s) per the master skill.
//   - Camera moves never repeat back-to-back (push_in / pull_out / slow_pan_lr /
//     slow_pan_rl / orbit_fake / gimbal_walk — 6 distinct types in rotation).
//   - On-screen text at brand-mandated moments: address title at 0.5s,
//     kinetic price flash 3.0–5.0s, kinetic reveal in final 5s.
//   - 3D "YOUR MORNING" overlay at 8.4–10.4s — sits in the mid-ground depth
//     plane of Beat 4 (great-room push-in with Cascade-view windows), tracked
//     to the same push_in scale curve the mid layer uses (1.0× pan, 1.0×
//     scale offset). CSS perspective(800px) rotateX(-5deg) translateZ(50px)
//     gives the floating-glass-pane read between the window mullions
//     (foreground) and the Three Sisters (background).
//
// DATA ACCURACY NOTE (per CLAUDE.md and ANTI_SLOP_MANIFESTO Rule 7):
//   Verified figures (sources documented):
//     - Address: 19496 TUMALO RESERVOIR RD (Supabase StreetNumber+StreetName)
//     - Price:   $1,350,000 (Supabase ListPrice = 1350000)
//     - Status:  FOR SALE (Supabase StandardStatus = "Active")
//     - Specs:   4 BD / 3 BA / 3,218 SF / 5 Acres — confirmed by listing
//                agent (Matt) on 2026-04-26. Top-level Supabase columns are
//                null on this row but the agent has direct MLS access; this
//                trace stands as the verification of record.
//
// Photo set (15 unique, no reuse):
//   13 MLS picks: 1, 2, 9, 14, 16, 22, 26, 28, 30, 31, 45, 56, 58
//   2 personal:   water_feature, wildflowers (eagle cut per Matt 2026-04-26;
//                 deer cut per v2 brief)
//
// All depth maps live in public/v5_library/depth/tumalo/<photo_slug>/.

import React from 'react';
import {
  AbsoluteFill,
  Sequence,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import { CHARCOAL, CREAM, GOLD, NAVY, OFF_WHITE, FONT_SANS, FONT_SERIF } from './brand';
import { DepthParallaxBeat } from './components/DepthParallaxBeat';
import {
  LightLeakTransition,
  WhipPanTransition,
} from './components';
import { PhotoBeat } from './PhotoBeat';
import { CameraMoveOpts } from './cameraMoves';
import { clamp, easeOutCubic, easeOutQuart } from './easing';

const FPS = 30;
export const TUMALO_TOTAL_SEC = 42.6;

// 100 BPM = 1.667 beats/second = 0.6s per sub-beat.
// Cuts snap to multiples of SUB_BEAT_SEC.
const SUB_BEAT_SEC = 0.6;

type BeatDef = {
  photo: string;        // path under public/images/ for blurred backdrop fallback
  depthDir: string;     // path under public/images/ to bg.png/mid.png/fg.png
  startSec: number;     // beat start, snapped to 0.6s grid
  durationSec: number;  // beat duration, multiple of 0.6s
  move: CameraMoveOpts;
  vignetteLetterbox?: boolean;
  objectPosition?: string;
  /** Disable built-in PhotoBeat crossfade in for this beat (used when wrapping
   *  in WhipPanTransition which controls the entry animation). */
  crossfadeIn?: number;
  crossfadeOut?: number;
  /** Skip depth parallax for this beat — render with flat <PhotoBeat> instead.
   *  Used when MiDaS produces unusable cuts (high-contrast silhouettes,
   *  recognizable wildlife, photos where the dark area is read as "near"
   *  and the depth-cut foreground slides off-frame at high pan intensity). */
  flat?: boolean;
};

// All paths are relative to public/images/ (which symlinks v5_library → ../v5_library)
const lib = (slug: string) => `v5_library/tumalo/${slug}`;
const depth = (slug: string) => `v5_library/depth/tumalo/${slug}`;

const BEATS: BeatDef[] = [
  // === HOOK (0.0 - 3.0s) — hero exterior at dusk + address overlay ========
  // Beat 1: 5 sub-beats (3.0s). vignetteLetterbox preserves the wide DJI
  // composition; mild push_in engages by frame 12 per master skill.
  { photo: lib('1-DJI_aerial_hero.jpg'),
    depthDir: depth('1-DJI_aerial_hero'),
    startSec: 0.0, durationSec: 3.0,
    move: { move: 'push_in', focal: 'center', intensity: 0.7 },
    vignetteLetterbox: true,
    crossfadeIn: 0 },

  // === INTRIGUE (3.0 - 8.4s) ==============================================
  // Beat 2: pull_out on the Three Sisters thru-window — viewer is pulled
  // back to see the wood-window framing reveal the snow peaks. Price flash
  // overlay fires during this beat.
  { photo: lib('16-twilight_DSC9560.jpg'),
    depthDir: depth('16-twilight_DSC9560'),
    startSec: 3.0, durationSec: 3.0,
    move: { move: 'pull_out', focal: 'center', intensity: 0.7 },
    vignetteLetterbox: true },
  // Beat 3: slow_pan_lr on Sisters from deck (wide aspect — uses pan range).
  { photo: lib('14-twilight_untitled.jpg'),
    depthDir: depth('14-twilight_untitled'),
    startSec: 6.0, durationSec: 2.4,
    move: { move: 'slow_pan_lr', focal: 'center', intensity: 1.0 } },

  // === TOUR (8.4 - 20.4s) =================================================
  // Beat 4: push_in — great room with Cascade view through windows.
  { photo: lib('26-int_DSC8932.jpg'),
    depthDir: depth('26-int_DSC8932'),
    startSec: 8.4, durationSec: 2.4,
    move: { move: 'push_in', focal: 'center', intensity: 1.0 } },
  // Beat 5: orbit_fake — kitchen narrow angle. (25% mark fires LightLeak
  // overlay at the 4→5 boundary — see Tumalo render block below.)
  { photo: lib('28-int_DSC8968.jpg'),
    depthDir: depth('28-int_DSC8968'),
    startSec: 10.8, durationSec: 2.4,
    move: { move: 'orbit_fake', focal: 'center', intensity: 0.8 } },
  // Beat 6: gimbal_walk lr — kitchen wide, walk through.
  // FLAT: MiDaS reads the dark fridge/oven concave area as foreground, and
  // gimbal_walk at intensity 0.9 with the 1.6× fg multiplier slides that
  // cut off-frame, exposing a CHARCOAL hole as a vertical tar smear. Plain
  // PhotoBeat with reduced intensity reads cleanly. Verified: tumalo_v3
  // 13.5s frame (the smear) → re-render shows clean kitchen.
  { photo: lib('30-int_DSC8983.jpg'),
    depthDir: depth('30-int_DSC8983'),
    startSec: 13.2, durationSec: 2.4,
    move: { move: 'gimbal_walk', focal: 'center', intensity: 0.5, direction: 'lr' },
    flat: true },
  // Beat 7: pull_out — primary suite opens up.
  { photo: lib('31-int_DSC8994.jpg'),
    depthDir: depth('31-int_DSC8994'),
    startSec: 15.6, durationSec: 2.4,
    move: { move: 'pull_out', focal: 'center', intensity: 0.6 } },
  // Beat 8: slow_pan_lr — covered porch deck.
  { photo: lib('22-int_DSC8333.jpg'),
    depthDir: depth('22-int_DSC8333'),
    startSec: 18.0, durationSec: 2.4,
    move: { move: 'slow_pan_lr', focal: 'center', intensity: 0.9 } },

  // === 50% PATTERN INTERRUPT (20.4 - 23.4s) — open deck w/ view ===========
  // WhipPanTransition wraps the incoming beat (and the outgoing beat 8 in a
  // separate Sequence) — kinetic snap from indoor to outdoor register.
  // Beat 9: slow_pan_rl. 5 sub-beats (3.0s) for dwell.
  { photo: lib('45-int_DSC9031.jpg'),
    depthDir: depth('45-int_DSC9031'),
    startSec: 20.4, durationSec: 3.0,
    move: { move: 'slow_pan_rl', focal: 'center', intensity: 1.0 },
    crossfadeIn: 0 },

  // === LIFESTYLE (23.4 - 31.0s) ==========================================
  // Beat 10: push_in — water feature focus pull.
  { photo: lib('lifestyle_water_feature.jpg'),
    depthDir: depth('lifestyle_water_feature'),
    startSec: 23.4, durationSec: 2.4,
    move: { move: 'push_in', focal: 'center', intensity: 0.8 },
    objectPosition: '60% 50%' },
  // Beat 11: slow_pan_rl — wildflower garden. (Eagle beat removed per Matt
  // 2026-04-26 — closing aerials now start at 28.2s instead of 30.6s.)
  { photo: lib('lifestyle_wildflowers.jpg'),
    depthDir: depth('lifestyle_wildflowers'),
    startSec: 25.8, durationSec: 2.4,
    move: { move: 'slow_pan_rl', focal: 'center', intensity: 1.0 } },

  // === CLOSING AERIALS (28.2 - 37.8s) ====================================
  // Beat 12 (was 13): push_in — aerial 3/4 angle.
  { photo: lib('56-DJI_aerial_5.jpg'),
    depthDir: depth('56-DJI_aerial_5'),
    startSec: 28.2, durationSec: 2.4,
    move: { move: 'push_in', focal: 'center', intensity: 0.6 } },
  // Beat 13 (was 14): orbit_fake — top-down geometry, subtle rotation.
  { photo: lib('58-DJI_aerial_4.jpg'),
    depthDir: depth('58-DJI_aerial_4'),
    startSec: 30.6, durationSec: 2.4,
    move: { move: 'orbit_fake', focal: 'center', intensity: 0.5 } },
  // Beat 14 (was 15): gimbal_walk rl — daytime back facade.
  { photo: lib('2-DJI_aerial_2.jpg'),
    depthDir: depth('2-DJI_aerial_2'),
    startSec: 33.0, durationSec: 2.4,
    move: { move: 'gimbal_walk', focal: 'center', intensity: 0.8, direction: 'rl' } },
  // Beat 15 (was 16): slow_pan_rl — dusk wide w/ Sisters silhouette into reveal.
  // FLAT: dusk sky has soft gradients that MiDaS struggles to layer cleanly;
  // produced a dark crescent artifact on the left at slow_pan_rl with the
  // bg layer's translation exposing a hole. Plain PhotoBeat reads cleanly.
  { photo: lib('9-DJI_aerial_3.jpg'),
    depthDir: depth('9-DJI_aerial_3'),
    startSec: 35.4, durationSec: 2.4,
    move: { move: 'slow_pan_rl', focal: 'center', intensity: 0.9 },
    flat: true,
    crossfadeOut: 0 },
];

// CINEMATIC v4: smooth pre-roll crossfade. Each beat's Sequence runs for
// (PREROLL + durationSec) seconds, starting PREROLL seconds before the beat's
// declared startSec. During the pre-roll window, the beat's animation is
// PAUSED at its t=0 state and the alpha fades in 0→1. The OUTGOING beat is at
// full alpha throughout (no exit fade), so the incoming beat covers it pixel-
// by-pixel through CSS compositing. After pre-roll, the beat plays normally
// at full alpha and ends at its Sequence boundary (no tail). This gives a
// real cinematic crossfade without the CHARCOAL bg-bleed bug or the ghost-
// overlap bug from prior iterations.
const PREROLL_SEC = 0.6;

// ─── Beat wrapper — picks DepthParallaxBeat or PhotoBeat per-beat ─────────
const BeatWrapper: React.FC<{ beat: BeatDef; preroll: number }> = ({
  beat,
  preroll,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const sequenceLocal = frame / fps;
  // Animation time inside the beat starts AFTER the pre-roll window.
  // During pre-roll (sequenceLocal < preroll), the beat sits at t=0 of its
  // own animation while alpha fades in.
  const beatLocal = Math.max(0, sequenceLocal - preroll);
  // Entry fade ramps 0→1 linearly over the pre-roll window. Linear (not
  // eased) so that incoming + outgoing alpha sums match cleanly.
  const entryAlpha = preroll > 0 ? clamp(sequenceLocal / preroll, 0, 1) : 1;
  // Override-only path: when a beat explicitly sets crossfadeIn, honor it
  // instead of the global pre-roll. (Used by Beat 1 and Beat 9 which start
  // hard at frame 0 / WhipPan boundary.)
  const explicitIn = beat.crossfadeIn;
  const effectiveIn = explicitIn ?? 0;       // 0 = use the pre-roll path above
  const effectiveOut = beat.crossfadeOut ?? 0;
  const Comp = beat.flat ? PhotoBeat : (DepthParallaxBeat as typeof PhotoBeat);
  return (
    <div style={{ opacity: entryAlpha, position: 'absolute', inset: 0 }}>
      <Comp
        photo={beat.photo}
        // @ts-expect-error PhotoBeat ignores depthDir
        depthDir={beat.depthDir}
        local={beatLocal}
        fps={fps}
        durationSec={beat.durationSec}
        move={beat.move}
        vignetteLetterbox={beat.vignetteLetterbox}
        objectPosition={beat.objectPosition}
        titlePosition="none"
        scrim="none"
        crossfadeIn={effectiveIn}
        crossfadeOut={effectiveOut}
      />
    </div>
  );
};

// ─── Address title overlay — animates in over Beat 1 ─────────────────────
const AddressTitle: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const t = frame / fps;
  // Title fades in 0–0.5s — fully visible by user-spec'd 0.5s mark.
  const alpha = clamp(t / 0.5, 0, 1);
  const ty = (1 - easeOutQuart(alpha)) * 22;
  // Hold steady from 0.9s until beat 1 ends at 3.0s, then fade out 2.6–2.9s.
  const exit = clamp((t - 2.6) / 0.4, 0, 1);
  const opacity = alpha * (1 - exit);
  return (
    <AbsoluteFill style={{ pointerEvents: 'none' }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          background:
            'linear-gradient(180deg, rgba(15,10,6,0.45) 0%, rgba(15,10,6,0.18) 50%, rgba(15,10,6,0.55) 100%)',
          opacity: opacity * 0.85,
        }}
      />
      <div
        style={{
          position: 'absolute',
          left: 90,
          right: 90,
          top: '50%',
          transform: `translateY(calc(-50% + ${-ty}px))`,
          opacity,
          textAlign: 'center',
        }}
      >
        <div
          style={{
            fontFamily: FONT_SERIF,
            fontSize: 88,
            lineHeight: 1.04,
            color: '#F8F4EA',
            letterSpacing: '-0.01em',
            textShadow: '0 4px 24px rgba(0,0,0,0.75), 0 2px 6px rgba(0,0,0,0.85)',
          }}
        >
          19496 TUMALO RESERVOIR
        </div>
        <div
          style={{
            marginTop: 22,
            fontFamily: FONT_SANS,
            fontWeight: 700,
            fontSize: 44,
            color: GOLD,
            letterSpacing: 5,
            textTransform: 'uppercase',
            textShadow: '0 2px 10px rgba(0,0,0,0.85)',
          }}
        >
          BEND · OREGON
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ─── Price flash — fires 3.0–5.0s during Beat 2 ──────────────────────────
const PriceFlash: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const t = frame / fps;
  // Sequence is 2s long. Bloom 0–0.5s, hold 0.5–1.5s, fade 1.5–2.0s.
  const bloomIn = clamp(t / 0.45, 0, 1);
  const fadeOut = clamp((t - 1.5) / 0.5, 0, 1);
  const alpha = easeOutCubic(bloomIn) * (1 - fadeOut);
  const scale = 0.94 + 0.06 * easeOutCubic(bloomIn);
  return (
    <AbsoluteFill style={{ pointerEvents: 'none' }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          alignItems: 'flex-end',
          justifyContent: 'center',
          paddingBottom: 280,
        }}
      >
        <div
          style={{
            transform: `scale(${scale.toFixed(4)})`,
            opacity: alpha,
            padding: '24px 56px',
            background: 'rgba(16, 39, 66, 0.78)',
            borderRadius: 14,
            border: `1px solid ${GOLD}`,
            backdropFilter: 'blur(8px)',
            textAlign: 'center',
            boxShadow: '0 12px 48px rgba(0,0,0,0.55)',
          }}
        >
          <div
            style={{
              fontFamily: FONT_SANS,
              fontWeight: 700,
              fontSize: 28,
              color: GOLD,
              letterSpacing: 6,
              textTransform: 'uppercase',
            }}
          >
            LIST PRICE
          </div>
          <div
            style={{
              marginTop: 10,
              fontFamily: FONT_SERIF,
              fontSize: 96,
              lineHeight: 1,
              color: '#F8F4EA',
              letterSpacing: '-0.01em',
              textShadow: '0 4px 18px rgba(0,0,0,0.55)',
            }}
          >
            $1,350,000
          </div>
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ─── Specs flash — 4 BD | 3 BA | 3,218 SF | 5 Acres, fires around beat 6 ─
const SpecsFlash: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const t = frame / fps;
  // Sequence is 2s long (13.2 – 15.2s). Bloom 0–0.4s, hold, fade 1.5–2.0s.
  const bloomIn = clamp(t / 0.4, 0, 1);
  const fadeOut = clamp((t - 1.5) / 0.5, 0, 1);
  const alpha = easeOutCubic(bloomIn) * (1 - fadeOut);
  const ty = (1 - easeOutQuart(bloomIn)) * 22;
  return (
    <AbsoluteFill style={{ pointerEvents: 'none' }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          alignItems: 'flex-end',
          justifyContent: 'center',
          paddingBottom: 280,
        }}
      >
        <div
          style={{
            transform: `translateY(${ty}px)`,
            opacity: alpha,
            padding: '20px 44px',
            background: 'rgba(16, 39, 66, 0.78)',
            borderRadius: 12,
            border: `1px solid ${GOLD}`,
            backdropFilter: 'blur(8px)',
            textAlign: 'center',
            boxShadow: '0 12px 40px rgba(0,0,0,0.55)',
          }}
        >
          <div
            style={{
              fontFamily: FONT_SANS,
              fontWeight: 700,
              fontSize: 52,
              color: '#F8F4EA',
              letterSpacing: 4,
              textTransform: 'uppercase',
              lineHeight: 1.1,
              textShadow: '0 2px 10px rgba(0,0,0,0.7)',
            }}
          >
            4 BD &nbsp;·&nbsp; 3 BA
          </div>
          <div
            style={{
              marginTop: 8,
              fontFamily: FONT_SANS,
              fontWeight: 600,
              fontSize: 38,
              color: GOLD,
              letterSpacing: 5,
              textTransform: 'uppercase',
              textShadow: '0 2px 8px rgba(0,0,0,0.7)',
            }}
          >
            3,218 SF &nbsp;·&nbsp; 5 ACRES
          </div>
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ─── 3D "YOUR MORNING" overlay — sits in mid-ground depth plane of Beat 4
// CINEMATIC v4: animated rotateX (-12° → -22° as the camera pushes in, so the
// text "settles" into the room depth), 8-layer extruded shadow stack giving
// real perceived depth (not just a flat off-white drop-shadowed decal), wider
// perspective. The text now READS as a 3D plane suspended in the room.
const MorningOverlay: React.FC<{ beatDurationSec: number }> = ({
  beatDurationSec,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const tOverlay = frame / fps;

  // Mid-layer push_in scale — must match DepthParallaxBeat push_in 0.16 ×
  // mid scaleMult 1.0. v4.1 multiplier still 1.0 for mid (only bg/fg
  // changed), so this formula is unchanged.
  const tInBeat = clamp(tOverlay / beatDurationSec, 0, 1);
  const midScale = 1.0 + 0.16 * easeOutCubic(tInBeat);

  // Animated rotateX: -12° at entry → -22° at peak as the camera pushes in.
  // The deepening tilt sells the 3D-plane-in-real-space read.
  const rotX = -12 - 10 * easeOutCubic(tInBeat);
  // Animated translateZ: 30px → 80px push toward camera (matches the dolly).
  const tz = 30 + 50 * easeOutCubic(tInBeat);

  // Entrance: 0.5s fade + 18px upward emergence.
  const entryT = clamp(tOverlay / 0.5, 0, 1);
  const entryAlpha = easeOutCubic(entryT);
  const entryY = (1 - easeOutQuart(entryT)) * 18;

  // Exit: fade out 1.5–2.0s.
  const exitT = clamp((tOverlay - 1.5) / 0.5, 0, 1);
  const opacity = entryAlpha * (1 - exitT);

  // 8-layer extruded shadow stack — each layer offset 1px down/right in a
  // dark color, simulating a real extruded 3D edge. The viewer perceives
  // this as a thick, solid 3D pane rather than flat 2D type with a glow.
  const extrusionLayers = Array.from({ length: 8 }, (_, k) => {
    const offset = k + 1;
    return `${offset}px ${offset}px 0 rgba(20, 12, 6, 0.95)`;
  }).join(', ');
  // Ambient halo on top of the extrusion to lift the front face off the
  // background and add atmospheric glow.
  const haloShadow =
    '0 0 1px rgba(0,0,0,0.6), 0 18px 38px rgba(0,0,0,0.55), 0 6px 12px rgba(0,0,0,0.6)';

  return (
    <AbsoluteFill style={{ pointerEvents: 'none', perspective: '1200px' }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          transform: `scale(${midScale.toFixed(4)})`,
          transformOrigin: '50% 50%',
        }}
      >
        <div
          style={{
            transform: `translateY(${entryY.toFixed(2)}px) rotateX(${rotX.toFixed(2)}deg) translateZ(${tz.toFixed(2)}px)`,
            transformStyle: 'preserve-3d',
            opacity,
            width: '70%',
            textAlign: 'center',
            fontFamily: FONT_SERIF,
            fontSize: 156,
            lineHeight: 0.94,
            color: OFF_WHITE,
            letterSpacing: '-0.005em',
            textShadow: `${extrusionLayers}, ${haloShadow}`,
          }}
        >
          YOUR
          <br />
          MORNING
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ─── Reveal — final 5s, kinetic stat block on navy ───────────────────────
const RevealInner: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const t = frame / fps;
  const navyAlpha = clamp(t / 0.5, 0, 1);
  const statusAlpha = clamp((t - 0.6) / 0.6, 0, 1);
  const statusScale = 1.2 - 0.2 * easeOutCubic(clamp((t - 0.6) / 0.6, 0, 1));
  const priceAlpha = clamp((t - 1.4) / 0.7, 0, 1);
  const priceTranslate = (1 - easeOutCubic(clamp((t - 1.4) / 0.7, 0, 1))) * 16;
  const addressAlpha = clamp((t - 2.3) / 0.7, 0, 1);
  const addressTranslate = (1 - easeOutCubic(clamp((t - 2.3) / 0.7, 0, 1))) * 12;
  return (
    <AbsoluteFill style={{ background: NAVY, opacity: navyAlpha }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
        }}
      >
        <div
          style={{
            fontFamily: FONT_SERIF,
            fontSize: 60,
            fontWeight: 700,
            color: GOLD,
            letterSpacing: '0.18em',
            opacity: statusAlpha,
            transform: `scale(${statusScale})`,
            marginBottom: 18,
          }}
        >
          FOR SALE
        </div>
        <div
          style={{
            fontFamily: FONT_SERIF,
            fontSize: 124,
            fontWeight: 400,
            color: CREAM,
            letterSpacing: '-0.01em',
            opacity: priceAlpha,
            transform: `translateY(${priceTranslate}px)`,
            marginBottom: 32,
          }}
        >
          $1,350,000
        </div>
        <div
          style={{
            fontFamily: FONT_SANS,
            fontSize: 30,
            fontWeight: 600,
            color: CREAM,
            letterSpacing: '0.18em',
            textTransform: 'uppercase',
            opacity: addressAlpha,
            transform: `translateY(${addressTranslate}px)`,
            textAlign: 'center',
            lineHeight: 1.5,
          }}
        >
          19496 TUMALO RESERVOIR RD
          <br />
          BEND, OREGON
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ─── Composition ─────────────────────────────────────────────────────────
export const Tumalo: React.FC = () => {
  // 25% mark = 11.25s — fires LightLeak in the Beat 4 → Beat 5 transition
  // window (Beat 5 starts 10.8s, transition centered ~11.0s, leak duration 0.35s).
  const lightLeakStart = Math.round((10.8 - 0.05) * FPS);
  const lightLeakDuration = Math.ceil(0.35 * FPS);

  // 50% mark — WhipPan: outgoing Beat 8 and incoming Beat 9 BOTH fire in
  // the same 0.3s window centered on Beat 9 start (20.4s). Window:
  // 20.1–20.4s. Outgoing slides out to right; incoming slides in from left.
  const whipDuration = 0.3;
  const whipBoundarySec = 20.4;                 // Beat 9 start
  const whipStart = Math.round((whipBoundarySec - whipDuration) * FPS);
  const whipFrames = Math.round(whipDuration * FPS);

  const beat8 = BEATS[7];
  const beat9 = BEATS[8];

  return (
    <AbsoluteFill style={{ background: CHARCOAL }}>
      {/* Photo beats — CINEMATIC v4 smooth pre-roll crossfade.
          Each beat (except Beat 1 which starts at t=0 with no preroll, and
          Beat 9 which is handed off from the WhipPan at exactly 20.4s)
          starts its Sequence PREROLL_SEC before its declared startSec. The
          BeatWrapper holds the beat at t=0 during pre-roll while alpha
          fades 0→1. The OUTGOING beat's Sequence ends at its declared end
          (no tail, no exit fade), so the incoming beat covers the outgoing
          pixel-by-pixel as it ramps to full opacity. This produces a real
          cinematic dissolve without the bg-bleed or ghost-overlap bugs from
          v3 iterations. */}
      {BEATS.map((beat, i) => {
        const useHardEntry = i === 0 || i === 8; // Beat 1 + Beat 9 (post-WhipPan)
        const preroll = useHardEntry ? 0 : PREROLL_SEC;
        const seqFrom = Math.round(Math.max(0, beat.startSec - preroll) * FPS);
        const seqEnd = i === 7
          ? whipStart
          : Math.round((beat.startSec + beat.durationSec) * FPS);
        const seqDuration = seqEnd - seqFrom;
        return (
          <Sequence
            key={i}
            from={seqFrom}
            durationInFrames={seqDuration}
          >
            <BeatWrapper beat={beat} preroll={preroll} />
          </Sequence>
        );
      })}

      {/* WhipPan window 20.1–20.4s — both layers fire simultaneously.
          Outgoing Beat 8 slides off right; incoming Beat 9 slides in from
          left. Render order: outgoing first, incoming on top so the new
          content lands on top as the slide completes. */}
      <Sequence from={whipStart} durationInFrames={whipFrames}>
        <WhipPanTransition mode="out" direction="rl" durationSec={whipDuration}>
          <BeatWrapper beat={beat8} preroll={0} />
        </WhipPanTransition>
      </Sequence>
      <Sequence from={whipStart} durationInFrames={whipFrames}>
        <WhipPanTransition mode="in" direction="rl" durationSec={whipDuration}>
          <BeatWrapper beat={beat9} preroll={0} />
        </WhipPanTransition>
      </Sequence>

      {/* 25% LightLeak overlay — bloom warm at the Beat 4 → 5 boundary. */}
      <Sequence from={lightLeakStart} durationInFrames={lightLeakDuration}>
        <LightLeakTransition durationSec={0.35} intensity="medium" position={{ x: '52%', y: '38%' }} />
      </Sequence>

      {/* Address title — 0.0–3.0s over Beat 1 */}
      <Sequence from={0} durationInFrames={Math.round(3.0 * FPS)}>
        <AddressTitle />
      </Sequence>

      {/* Price flash — 3.0–5.0s over Beat 2 */}
      <Sequence from={Math.round(3.0 * FPS)} durationInFrames={Math.round(2.0 * FPS)}>
        <PriceFlash />
      </Sequence>

      {/* 3D "YOUR MORNING" overlay — 8.4–10.4s, mid-ground depth plane of Beat 4 */}
      <Sequence from={Math.round(8.4 * FPS)} durationInFrames={Math.round(2.0 * FPS)}>
        <MorningOverlay beatDurationSec={BEATS[3].durationSec} />
      </Sequence>

      {/* Specs flash — 13.2–15.2s over Beat 6 (kitchen wide) */}
      <Sequence from={Math.round(13.2 * FPS)} durationInFrames={Math.round(2.0 * FPS)}>
        <SpecsFlash />
      </Sequence>

      {/* Reveal — final 5.0s on navy (was 40.0s; shifted to 37.6s after
          eagle beat removal trimmed 2.4s from the closing block). */}
      <Sequence from={Math.round(37.6 * FPS)} durationInFrames={Math.round(5.0 * FPS)}>
        <RevealInner />
      </Sequence>
    </AbsoluteFill>
  );
};

// PhotoBeat is now actively used for `flat: true` beats (eagle, kitchen wide
// gimbal_walk, dusk wide closing) where MiDaS depth cuts produced visible
// artifacts. See BeatWrapper above.
