#!/usr/bin/env node
/**
 * Create the actual Meta Lead-Gen ad from an ad-spec.json file.
 *
 * Reads the spec generated by build-fb-ad.mjs, uploads the rendered video
 * from the asset library, creates the full campaign/ad set/ad creative/ad
 * hierarchy, and leaves everything PAUSED until --launch is passed.
 *
 * Usage:
 *   node --env-file=.env.local scripts/create-fb-ad.mjs --city bend --period 2026-04
 *   node --env-file=.env.local scripts/create-fb-ad.mjs --city bend --period 2026-04 --launch
 *
 * Options:
 *   --city    <city>      City slug — must match what was passed to build-fb-ad.mjs
 *   --period  <YYYY-MM>   Report period
 *   --launch              Flip campaign + ad set + ad to ACTIVE after creation
 *   --video   <path>      Explicit path to video file (skip asset library lookup)
 *   --dry-run             Print what would be created without calling the API
 *
 * Requires:
 *   META_AD_ACCOUNT_ID, META_PAGE_ID / META_FB_PAGE_ID, META_PAGE_ACCESS_TOKEN / META_PAGE_TOKEN
 *   NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 *   FUB_API_KEY, FUB_PIPELINE_ID
 *
 * Fair Housing Act compliance:
 *   Special ad category HOUSING is enforced by the API client — cannot be skipped.
 *
 * QA checklist (run before --launch):
 *   [ ] Campaign objective = LEAD_GENERATION
 *   [ ] Special ad category = HOUSING
 *   [ ] Lead form attached with all required fields
 *   [ ] Ad copy passes banned-word check
 *   [ ] Daily budget set correctly
 *   [ ] Status = PAUSED (review before activating)
 *   [ ] FUB webhook verified at /api/meta/lead-webhook
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  uploadVideo,
  createCampaign,
  createAdSet,
  createAdCreative,
  createAd,
  setAdStatus,
  MetaMarketingError,
} from '../lib/meta-marketing-api.mjs'

import { getOrCreateForm } from '../lib/lead-form-template.mjs'
import { search, register } from '../lib/asset-library.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ---------------------------------------------------------------------------
// CLI arg parsing
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const out = { _: [] }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a.startsWith('--')) {
      const eq = a.indexOf('=')
      if (eq >= 0) {
        out[a.slice(2, eq)] = a.slice(eq + 1)
      } else {
        const next = argv[i + 1]
        if (next && !next.startsWith('--')) {
          out[a.slice(2)] = next
          i++
        } else {
          out[a.slice(2)] = true
        }
      }
    } else {
      out._.push(a)
    }
  }
  return out
}

const args = parseArgs(process.argv.slice(2))

const city = args.city?.toString().toLowerCase().trim()
const period = args.period?.toString().trim()
const shouldLaunch = !!args.launch
const explicitVideoPath = args.video?.toString().trim() || null
const dryRun = !!args['dry-run']

if (!city) {
  console.error('Error: --city is required')
  process.exit(1)
}
if (!period || !/^\d{4}-\d{2}$/.test(period)) {
  console.error('Error: --period is required in YYYY-MM format')
  process.exit(1)
}

// ---------------------------------------------------------------------------
// Env preflight — Meta + FUB keys must be present before we do any work
// ---------------------------------------------------------------------------

function checkEnvPreflight() {
  const missing = []

  const metaAccount = (process.env.META_AD_ACCOUNT_ID || '').trim()
  const metaPage = (process.env.META_PAGE_ID || process.env.META_FB_PAGE_ID || '').trim()
  const metaToken = (process.env.META_PAGE_ACCESS_TOKEN || process.env.META_PAGE_TOKEN || '').trim()
  const fubKey = (process.env.FUB_API_KEY || process.env.FOLLOWUPBOSS_API_KEY || '').trim()

  if (!metaAccount) missing.push('META_AD_ACCOUNT_ID (format: act_XXXXXXXXX — find in Ads Manager → Account Overview)')
  if (!metaPage) missing.push('META_PAGE_ID or META_FB_PAGE_ID (Ryan Realty Facebook Page ID)')
  if (!metaToken) missing.push('META_PAGE_ACCESS_TOKEN or META_PAGE_TOKEN (long-lived page access token)')
  if (!fubKey) missing.push('FUB_API_KEY or FOLLOWUPBOSS_API_KEY (Follow-Up Boss API → Settings → API)')

  if (missing.length > 0) {
    console.error('\n[create-fb-ad] Missing required env vars:')
    for (const m of missing) {
      console.error(`  • ${m}`)
    }
    console.error('\nAdd these to .env.local and re-run.')
    process.exit(1)
  }

  const pipelineId = (process.env.FUB_PIPELINE_ID || '').trim()
  if (!pipelineId) {
    console.warn('[create-fb-ad] WARNING: FUB_PIPELINE_ID not set. Leads will enter FUB without a pipeline. Add FUB_PIPELINE_ID=<id> to .env.local.')
  }
}

// ---------------------------------------------------------------------------
// Read ad spec
// ---------------------------------------------------------------------------

async function readAdSpec(city, period) {
  const slug = city.replace(/\s+/g, '-').toLowerCase()
  const specPath = resolve(ROOT, 'out', 'fb-ad', slug, period, 'ad-spec.json')
  if (!existsSync(specPath)) {
    throw new Error(
      `Ad spec not found at ${specPath}. ` +
      `Run build-fb-ad.mjs first: node --env-file=.env.local scripts/build-fb-ad.mjs --city ${city} --period ${period}`
    )
  }
  const raw = await readFile(specPath, 'utf8')
  return { spec: JSON.parse(raw), specPath, slug }
}

// ---------------------------------------------------------------------------
// Find rendered video in asset library
// ---------------------------------------------------------------------------

async function findRenderedVideo(spec, slug, explicitPath) {
  if (explicitPath) {
    if (!existsSync(explicitPath)) {
      throw new Error(`Explicit video path not found: ${explicitPath}`)
    }
    console.log(`[create-fb-ad] Using explicit video: ${explicitPath}`)
    return explicitPath
  }

  console.log('[create-fb-ad] Searching asset library for rendered short-form video...')

  const hint = spec.asset_library_search || {}
  const results = await search({
    type: hint.type || 'render',
    geo: hint.geo || [slug, 'central-oregon'],
    subject: hint.subject || ['market-report', 'short-form'],
    limit: 10,
  })

  // Filter to MP4s only, prefer most recent
  const videos = results.filter(r => {
    const fp = r.file_path || ''
    return fp.endsWith('.mp4') || r.notes?.includes('mp4')
  })

  if (videos.length === 0) {
    // Also try without subject filter — maybe it's tagged differently
    const broad = await search({
      type: 'render',
      geo: [slug],
      limit: 20,
    })
    const mp4s = broad.filter(r => (r.file_path || '').endsWith('.mp4'))
    if (mp4s.length > 0) {
      const best = mp4s[0]
      const fp = resolve(ROOT, best.file_path)
      if (existsSync(fp)) {
        console.log(`[create-fb-ad] Found video (broad search): ${fp}`)
        return fp
      }
    }
    throw new Error(
      `No rendered MP4 found in asset library for city="${slug}" period="${spec.period}".\n` +
      `Either:\n` +
      `  1. Run the market report video pipeline first to generate and register the render, or\n` +
      `  2. Pass --video <path> to specify the video manually.`
    )
  }

  const best = videos[0]
  const fp = resolve(ROOT, best.file_path)
  if (!existsSync(fp)) {
    throw new Error(`Asset library references ${best.file_path} but file not found on disk. Run the render pipeline first.`)
  }

  console.log(`[create-fb-ad] Found video: ${fp} (asset ${best.id})`)
  return fp
}

// ---------------------------------------------------------------------------
// Save creation result
// ---------------------------------------------------------------------------

async function saveResult(slug, period, result) {
  const outDir = resolve(ROOT, 'out', 'fb-ad', slug, period)
  await mkdir(outDir, { recursive: true })
  const outPath = resolve(outDir, 'ad-creation-result.json')
  await writeFile(outPath, JSON.stringify(result, null, 2))
  console.log(`[create-fb-ad] Result saved to: ${outPath}`)
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log('\n=== Create FB Lead-Gen Ad ===')
  console.log(`City: ${city} | Period: ${period} | Launch: ${shouldLaunch}`)
  if (dryRun) console.log('(dry-run — will not call Meta API)')
  console.log()

  // Preflight env check
  checkEnvPreflight()

  // Read ad spec
  console.log('[1/8] Reading ad spec...')
  const { spec, specPath, slug } = await readAdSpec(city, period)
  console.log(`      Loaded: ${specPath}`)
  console.log(`      Campaign: ${spec.campaign.name}`)

  // Verify the spec data trace
  if (spec.verification_trace) {
    const vt = spec.verification_trace
    console.log(`\n      Verification trace:`)
    console.log(`        Source: ${vt.source}`)
    console.log(`        median_sale_price: ${vt.values.median_sale_price}`)
    console.log(`        yoy_pct: ${vt.values.median_sale_price_yoy_pct}`)
    console.log(`        fetched_at: ${vt.fetched_at}`)
    console.log()
  }

  // Find the rendered video
  console.log('[2/8] Locating rendered video...')
  const videoPath = await findRenderedVideo(spec, slug, explicitVideoPath)

  if (dryRun) {
    console.log('\n[dry-run] Would create:')
    console.log(JSON.stringify({
      video: videoPath,
      campaign: spec.campaign,
      ad_set: { ...spec.ad_set, targeting: '(targeting object)' },
      creative: spec.creative,
      ad: spec.ad,
    }, null, 2))
    console.log('\n[dry-run] No API calls made.')
    return
  }

  // Get the page ID from env (required for creative)
  const pageId = (process.env.META_PAGE_ID || process.env.META_FB_PAGE_ID || '').trim()

  // Upload video to Meta
  console.log('[3/8] Uploading video to Meta ad account...')
  const { id: videoId } = await uploadVideo(videoPath)
  console.log(`      Video ID: ${videoId}`)

  // Get/create the lead form
  console.log('[4/8] Getting/creating lead form...')
  const formId = await getOrCreateForm()
  console.log(`      Form ID: ${formId}`)

  // Create campaign
  console.log('[5/8] Creating campaign...')
  const { id: campaignId } = await createCampaign({
    name: spec.campaign.name,
  })

  // Create ad set
  console.log('[6/8] Creating ad set...')
  const { id: adSetId } = await createAdSet({
    campaign_id: campaignId,
    name: spec.ad_set.name,
    daily_budget: spec.ad_set.daily_budget_cents,
    targeting: spec.ad_set.targeting,
    start_time: spec.ad_set.start_time,
    end_time: spec.ad_set.end_time,
  })

  // Create ad creative
  console.log('[7/8] Creating ad creative...')
  const { id: creativeId } = await createAdCreative({
    video_id: videoId,
    page_id: pageId,
    primary_text: spec.creative.primary_text,
    headline: spec.creative.headline,
    description: spec.creative.description,
    call_to_action: {
      type: spec.creative.call_to_action_type || 'SIGN_UP',
      value: { lead_gen_form_id: formId },
    },
    name: `${spec.campaign.name} — Creative`,
  })

  // Create ad
  console.log('[8/8] Creating ad...')
  const { id: adId } = await createAd({
    ad_set_id: adSetId,
    creative_id: creativeId,
    name: spec.ad.name,
  })

  // Preview URL
  const adAccountId = (process.env.META_AD_ACCOUNT_ID || '').replace('act_', '')
  const previewUrl = `https://www.facebook.com/ads/manager/creation/creation/?act=${adAccountId}&campaign_id=${campaignId}&ad_set_id=${adSetId}&ad_id=${adId}`

  // Auto-register in asset library
  console.log('\nRegistering in asset library...')
  try {
    await register(videoPath, {
      type: 'render',
      source: 'render-output',
      source_id: `fb-ad:${city}:${period}`,
      geo: [slug, 'central-oregon'],
      subject: ['facebook-ad', 'lead-gen', 'market-report'],
      notes: `Meta Marketing campaign ${campaignId}, ad_set ${adSetId}, ad ${adId}`,
    })
  } catch (err) {
    console.warn(`  (asset library registration skipped: ${err.message})`)
  }

  // Assemble result
  const result = {
    created_at: new Date().toISOString(),
    city,
    period,
    campaign_id: campaignId,
    ad_set_id: adSetId,
    creative_id: creativeId,
    ad_id: adId,
    form_id: formId,
    video_id: videoId,
    status: 'PAUSED',
    preview_url: previewUrl,
    copy: spec.creative,
    budget: spec.ad_set,
  }

  // Save result JSON
  await saveResult(slug, period, result)

  // Launch if requested
  if (shouldLaunch) {
    console.log('\nLaunching campaign...')
    await setAdStatus(campaignId, 'ACTIVE', 'campaign')
    await setAdStatus(adSetId, 'ACTIVE', 'adset')
    await setAdStatus(adId, 'ACTIVE', 'ad')
    result.status = 'ACTIVE'
    console.log('Campaign is now ACTIVE. Leads will route to FUB starting now.')
  }

  // Final summary
  console.log('\n' + '='.repeat(60))
  console.log('Facebook Lead-Gen Ad — DRAFT (PAUSED)')
  console.log('='.repeat(60))
  console.log(`Campaign: ${spec.campaign.name}`)
  console.log(`Daily budget: $${spec.ad_set.daily_budget_dollars}/day for ${spec.ad_set.run_days} days`)
  console.log(`Audience: ${spec.city_display} ${spec.ad_set.targeting?.geo_locations?.custom_locations?.[0]?.radius ?? 25}mi radius, age 25-65, real estate interest`)
  console.log()
  console.log(`Primary text: "${spec.creative.primary_text}"`)
  console.log(`Headline: ${spec.creative.headline}`)
  console.log(`CTA: ${spec.creative.call_to_action_type} → opens lead form ${formId}`)
  console.log()
  console.log(`Campaign ID: ${campaignId}`)
  console.log(`Ad ID: ${adId}`)
  console.log()
  console.log(`Preview: ${previewUrl}`)
  console.log()
  if (!shouldLaunch) {
    console.log('Status: PAUSED — leads are NOT flowing yet.')
    console.log(`To activate: node --env-file=.env.local scripts/create-fb-ad.mjs --city ${city} --period ${period} --launch`)
    console.log()
    console.log('Pre-launch QA checklist:')
    console.log('  [ ] Review ad in Ads Manager: ' + previewUrl)
    console.log('  [ ] Verify lead form fields (first/last/email/phone/intent)')
    console.log('  [ ] Confirm FUB webhook is configured at /api/meta/lead-webhook')
    console.log('  [ ] Confirm daily budget ($' + spec.ad_set.daily_budget_dollars + '/day)')
    console.log('  [ ] Confirm run length (' + spec.ad_set.run_days + ' days from ' + new Date(spec.ad_set.start_time).toLocaleDateString() + ')')
  } else {
    console.log('Status: ACTIVE — campaign is live. Leads will route to FUB pipeline ' + (process.env.FUB_PIPELINE_ID || '(unset)'))
  }
  console.log('='.repeat(60))
}

main().catch(err => {
  console.error('\n[create-fb-ad] Fatal error:', err instanceof MetaMarketingError
    ? `${err.message} (Meta code: ${err.code}, type: ${err.type})`
    : err.message || err
  )
  process.exit(1)
})
