-- Weekly (and optional daily) market reports: pending and closed by city.
-- Reports are generated by cron; image stored in Storage bucket "banners" or "reports".

CREATE TABLE IF NOT EXISTS market_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  period_type text NOT NULL CHECK (period_type IN ('daily', 'weekly')),
  period_start date NOT NULL,
  period_end date NOT NULL,
  title text NOT NULL,
  image_storage_path text,
  content_html text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_market_reports_slug ON market_reports (slug);
CREATE INDEX IF NOT EXISTS idx_market_reports_created ON market_reports (created_at DESC);

ALTER TABLE market_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read market_reports" ON market_reports;
CREATE POLICY "Public read market_reports"
  ON market_reports FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Service role manage market_reports" ON market_reports;
CREATE POLICY "Service role manage market_reports"
  ON market_reports FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE market_reports IS 'Auto-generated market reports (pending/closed by city) for sharing and blog.';
