-- Rich place content for city, community (subdivision), and neighborhood landing pages.
-- Each place gets a comprehensive content record with structured sections covering
-- overview, history, schools, outdoor activities, dining, shopping, transportation,
-- demographics, events, and additional structured data.

CREATE TABLE IF NOT EXISTS place_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Place identification: "city", "community", or "neighborhood"
  place_type text NOT NULL CHECK (place_type IN ('city', 'community', 'neighborhood')),

  -- Unique key for the place. For cities: slugified city name (e.g. "bend").
  -- For communities: entity_key format "city:subdivision" (e.g. "bend:broken-top").
  -- For neighborhoods: "city:neighborhood" (e.g. "bend:northwest-crossing").
  place_key text NOT NULL,

  -- Display name
  place_name text NOT NULL,
  city_name text,

  -- Content sections (all optional, generated by AI and editable by admin)
  overview text,
  history text,
  lifestyle text,
  schools text,
  outdoor_recreation text,
  dining text,
  shopping text,
  arts_culture text,
  transportation text,
  healthcare text,
  events_festivals text,
  family_life text,
  real_estate_overview text,

  -- Structured data stored as JSONB for flexibility
  -- e.g. { "items": [{"name": "Bend Senior High", "type": "public", "grades": "9-12", "rating": "7/10"}] }
  schools_data jsonb,
  -- e.g. { "items": [{"name": "Deschutes Brewery", "cuisine": "American", "price": "$$"}] }
  dining_data jsonb,
  -- e.g. { "items": [{"name": "Phil's Trail", "type": "Mountain Biking", "difficulty": "Moderate"}] }
  recreation_data jsonb,
  -- e.g. { "items": [{"name": "Bend Farmers Market", "when": "June-October, Wednesdays"}] }
  events_data jsonb,

  -- SEO fields
  seo_title text,
  seo_description text,
  seo_keywords text[],

  -- FAQs for structured data / on-page display
  -- e.g. [{"question": "...", "answer": "..."}]
  faqs jsonb,

  -- Generation metadata
  generated_at timestamptz,
  generated_by text,        -- e.g. "grok-2-1212", "manual"
  last_edited_at timestamptz,
  last_edited_by text,      -- user ID or "system"

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  UNIQUE(place_type, place_key)
);

CREATE INDEX IF NOT EXISTS idx_place_content_place_type ON place_content(place_type);
CREATE INDEX IF NOT EXISTS idx_place_content_place_key ON place_content(place_key);
CREATE INDEX IF NOT EXISTS idx_place_content_city_name ON place_content(city_name);

ALTER TABLE place_content ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "place_content_read_all"
  ON place_content FOR SELECT
  USING (true);
